export const COMMON_DIALOG_TOGGLE = "COMMON_DIALOG_TOGGLE";
export const COMMON_DIALOG_VALIDATION_TOGGLE = "COMMON_DIALOG_VALIDATION_TOGGLE";
export const CART_DATA_LOADED = "CART_DATA_LOADED";
export const CART_DATA_LOAD_ERROR = "CART_DATA_LOAD_ERROR";
export const CART_PRODUCT_INCREASE = "CART_PRODUCT_INCREASE";
export const CART_PRODUCT_DECREASE = "CART_PRODUCT_DECREASE";
export const CART_PRODUCT_DELETE = "CART_PRODUCT_DELETE";
export const CART_PRODUCT_ADD = "CART_PRODUCT_ADD";